# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
# requires /.gitlab/base.yml

Symfony security check:
    extends: .long-running
    stage: unit
    needs: []
    before_script: []
    script:
        - composer install --no-interaction --no-scripts
        - >
            if [[ "$(arch)" == "aarch64" ]]; then
                export ARCH=arm64
                export SHA256SUM=d2c0bd8b3f6059e55a55ece56461d04728eeaad73ece902a8e8078d287721eb3
            else
                export ARCH=amd64
                export SHA256SUM=e5b12488ca78bc07c149e9352278bf10667b88a8461caac10154f9a6f5476369
            fi
        - curl --location --output local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_${ARCH}
        - echo "${SHA256SUM}  local-php-security-checker" > local-php-security-checker.sha256
        - sha256sum --check local-php-security-checker.sha256
        - chmod +x local-php-security-checker
        - ./local-php-security-checker
